### ISSUE TITLE
How to add more questions?

### ISSUE THREAD

**Issue by h4cc** [certificationy/symfony-pack#14]
First of all, thanks for this wonderful resource!
I am currently learning also using this book: https://leanpub.com/symfony-selfstudy
There are some questions and topics in there, that are not covered by this pack.

Because of all the copyright stuff and other unclear things i want to know:
__How to to add more questions to this pack?__

Simply copying from the book might be not a good idea :)

**Comment by mickaelandrieu** [comment]
ping @raulfraile, I will accept theses questions if Raul agree.

Else you can add your owns questions, you only need to update the yaml files. 
But, as I don't have a copy of this book, I can't check if questions come from "illegal" sources or not :/

**Comment by raulfraile** [comment]
Hey,

Thanks @h4cc for buying my book, I really hope you are enjoying it :) As you pointed out, the book and all its contents are copyrighted. I love open source and I do it as much as I can, but I put a lot of effort and time to create the book and I think the price is fair. So, I'm not ok with copying questions directly from the book but I don't mind if you take some ideas to improve this repository with new questions. 

@mickaelandrieu you were very nice allowing me to use questions from this pack in the book. I decided not do it as I tried to follow a different approach and also wouldn't be fair with the people buying the book. Anyway, I would like to give you a free copy of the book for your hard work creating this great resource. Please, send me an email to raulfraile[at]gmail[dot]com so I can give you a coupon :)

**Comment by mickaelandrieu** [comment]
@raulfraile I buied your book yesterday night :p but thank you  :)

I just get a look to your book and in my opinion it's a very useful resource to train the certification and learn about Symfony framework. Your questions are *very* hard, my score on the first serie was dramaticaly low o_O

Be sure I won't accept any question related to your ebook (*except* if the question appears after, I mean your ebook can be updated with new questions :) ). I will add a CONTRIBUTING.md with a note on this specific point: I love open source, and I respect copyrights.

**Comment by h4cc** [comment]
Thanks for your answers!
If i find a not already covered topic, i will try to come up with a question myself.

Issue can be closed :dancer:
