### ISSUE TITLE
Symfony 3 Certification Questions

### ISSUE THREAD

**Issue by h4cc** [certificationy/symfony-pack#21]
Symfony 3 has been released :smiley: and a new certification has been announced.

Is there a plan to provide the sf3 questions?

Maybe we start adding a info for which version the pack/files/questions are related.

**Comment by mickaelandrieu** [comment]
yup ! you can take a look to the Symfony 3 certification program exam topic, and suggest questions.

But, from my point of view, only few questions will be Symfony 3 related: do we realy need a new "deck" ? I will accept Symfony 3 questions in the actual deck,  on a dedicated Symfony3 category for now.

When Symfony3 will be the most used version, I will probably create a new deck and rename the actual deck ``symfony2-pack``.

**Comment by mickaelandrieu** [comment]
Done => https://github.com/certificationy/symfony-pack/commit/1bb48914fd744b27acf892e428d3567ae47fd193 thank you @h4cc
