### ISSUE TITLE
Twig path() question

### ISSUE THREAD

**Issue by mazhuravlev** [certificationy/symfony-pack#35]
[Question](https://github.com/certificationy/symfony-pack/blob/af9e057b402b242d1a7d365335f61782a80510b7/data/templating.yml#L178-L181) : True or false ? path() Twig function generates absolute urls.

According to [source](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Bridge/Twig/Extension/RoutingExtension.php#L45), RoutingExtension::path() generates not urls, but **paths**, and those are absolute by default, but can be made relative by setting the third parameter true. Signature of the helper is:
`path($name, $parameters = array(), $relative = false)`

**Comment by mickaelandrieu** [comment]
Should be ``True or false ? path() Twig function generates absolute *paths*.``

Good luck with the certification ! :)

**Comment by mazhuravlev** [comment]
Thank you!

The problem is path() can generate both relative and absolute paths. The question can be
```
What Twig path() function does generate?
  - absolute path (true)
  - relative path (true)
  - absolute url (false)
```

Also the difference between url and path is very subtle (RFC 1808 has [URL BNF](http://www.faqs.org/rfcs/rfc1808.html))
```
   URL         = ( absoluteURL | relativeURL )
   absoluteURL = generic-RL | ( scheme ":" *( uchar | reserved ) )
   generic-RL  = scheme ":" relativeURL
   relativeURL = net_path | abs_path | rel_path
   abs_path    = "/"  rel_path
   rel_path    = [ path ] [ ";" params ] [ "?" query ]
   path        = fsegment *( "/" segment )
   fsegment    = 1*pchar
   segment     =  *pchar
```

**Comment by mickaelandrieu** [comment]
If we look at [docs](http://symfony.com/doc/2.7/templating.html#linking-to-pages), ``path()`` sounds recommended to generate relative urls/paths when ``url()`` is recommended for absolute urls.

In my opinion this is a mistake, and ``path()`` should be avoided and ``url()`` always used instead.

How about:

```yaml
True or false ? url() function generates absolute urls by default.

- true (true)
- false (false)
```

What do you think ?

**Comment by mazhuravlev** [comment]
According to the [UrlGeneratorInterface source](https://github.com/symfony/symfony/blob/2.3/src/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php) url() can generate only absolute urls, like:
```
https://github.com/certificationy/symfony-pack (this one is true 'absolute url')
//github.com/certificationy/symfony-pack  (also called 'network path', will inherit current schema)
```
And path() can generate absolute and relative paths:
```
/certificationy/symfony-pack (absolute, when requested, will be appended to the hostname)
issues (relative, will be appended to current path)
```

Urls contain host (github.com), paths do not. Paths inherit current host. When some app is located on a single domain, there is no need to use urls in it, paths will suffice. But when link is supposed to be sent by mail, for example, it must be a full url.

**Comment by mickaelandrieu** [comment]
Ok, I close the issue for now.

Don't hesitate to make a pull request if you think it's worth :)
