### ISSUE TITLE
Document all PSRs 

### ISSUE THREAD

**Issue by mickaelandrieu** [certificationy/symfony-pack#48]
It could be useful to have basic knowledges about already validated PSR.

AFAIK, Symfony follows all validated PSRS and the PSR 11 (that will be accepted or is accepted?)
http://www.php-fig.org/psr/

ping @scaule if you want to contribute ? :)

**Comment by scaule** [comment]
Yes, I'm working on PSR-3 and 4 atm ;)

**Comment by mickaelandrieu** [comment]
Thank you @scaule, happy to have new contributions soon ^^
