### ISSUE TITLE
HTTP: Safe HTTP methods

### ISSUE THREAD

**Issue by a-menshchikov** [certificationy/symfony-pack#90]
Why TRACE and OPTIONS methods specified as safe (whereas it is not: https://datatracker.ietf.org/doc/html/rfc2616#section-9.1.1)?

**Comment by mickaelandrieu** [comment]
Hmm, not sure as I'm not the contributor of this question...

https://www.mscharhag.com/api-design/http-idempotent-safe#:~:text=Safe%20HTTP%20methods,%2C%20HEAD%2C%20OPTIONS%20and%20TRACE.
